/**
 * Generated TypeScript contract bindings.
 *
 * @generated by `cargo xtask generate`. Do not edit by hand.
 * Regenerate with `cargo xtask generate` after changing a schema under
 * `schemas/`, and verify with `cargo xtask generate --check`.
 */

/** Lifecycle state. `degraded` means the engine is serving requests with reduced capability and the detail field explains what is missing. */
export type EngineReadinessState =
  | "starting"
  | "ready"
  | "degraded"
  | "stopping"
  | "stopped";

/**
 * Engine readiness.
 *
 * What the engine reports about its own lifecycle so the shell can decide whether to send work. No command is accepted before handshake completion, and readiness is not authorization (108 sections 6 and 11).
 *
 * Canonical schema: `mirae://ipc/v1/engine-readiness`.
 */
export interface EngineReadiness {
  /** Lifecycle state. `degraded` means the engine is serving requests with reduced capability and the detail field explains what is missing. */
  readonly state: EngineReadinessState;
  /** Major protocol version this engine speaks. */
  readonly protocolMajor: number;
  /** Minor protocol version this engine speaks. */
  readonly protocolMinor: number;
  /** Identifies one engine process lifetime. A reconnecting client presents the last session id it saw, and a different value means its replicated state is stale. */
  readonly engineSessionId: string;
  /** Optional safe explanation for a degraded or stopping state. Never carries panic text, secrets, or machine paths (108 section 14). */
  readonly detail?: string;
}

/** Maximum accepted length of `engineSessionId`, for bounded decoding. */
export const ENGINE_READINESS_ENGINE_SESSION_ID_MAX_LENGTH = 64;

/** Maximum accepted length of `detail`, for bounded decoding. */
export const ENGINE_READINESS_DETAIL_MAX_LENGTH = 256;

/** The process role claiming the connection. Authentication proves the caller launched with a credential; authorization by role is separate. */
export type HelloRole =
  | "shell"
  | "control_ui"
  | "extension_host"
  | "test";

/**
 * Hello.
 *
 * The first message a client sends. It states the process role, the protocol range it supports, and the ephemeral launch credential proving the engine's parent started it. No command is accepted before the handshake completes (108 sections 6 and 11).
 *
 * Canonical schema: `mirae://ipc/v1/hello`.
 */
export interface Hello {
  /** The process role claiming the connection. Authentication proves the caller launched with a credential; authorization by role is separate. */
  readonly role: HelloRole;
  /** Lowest protocol major version the client can speak. */
  readonly protocolMajorMin: number;
  /** Highest protocol major version the client can speak. */
  readonly protocolMajorMax: number;
  /** Highest minor version the client supports within its maximum major version. */
  readonly protocolMinorMax: number;
  /** Hex-encoded ephemeral launch credential. Never logged and never included in diagnostics. */
  readonly credential: string;
  /** Client build identity, recorded so a merged log can show mismatched builds. */
  readonly buildId: string;
}

/** Maximum accepted length of `credential`, for bounded decoding. */
export const HELLO_CREDENTIAL_MAX_LENGTH = 128;

/** Maximum accepted length of `buildId`, for bounded decoding. */
export const HELLO_BUILD_ID_MAX_LENGTH = 64;

/**
 * Protocol version.
 *
 * The engine and shell protocol version. A major mismatch means an incompatible protocol and the connection is rejected; minor versions may add optional messages or fields, and the selected minor is the highest mutually supported one (108 section 8).
 *
 * Canonical schema: `mirae://ipc/v1/protocol-version`.
 */
export interface ProtocolVersion {
  /** Incompatible protocol generation. A peer that does not support this exact major version must be rejected. */
  readonly major: number;
  /** Backward-compatible revision within the major version. A higher minor may add optional messages and fields only. */
  readonly minor: number;
}

/** The only accepted value of `major`. */
export const PROTOCOL_VERSION_MAJOR = 1;

/** The only accepted value of `minor`. */
export const PROTOCOL_VERSION_MINOR = 0;

/** Why the connection was refused. `unauthenticated` never distinguishes a missing credential from a wrong one. */
export type RejectReason =
  | "unauthenticated"
  | "protocol_major_mismatch"
  | "malformed_hello"
  | "role_not_permitted"
  | "engine_not_ready";

/**
 * Reject.
 *
 * The engine's answer to a Hello it will not accept. The reason is a stable code so a client can act on it; the detail is a safe sentence and never says which part of a credential was wrong (108 section 14).
 *
 * Canonical schema: `mirae://ipc/v1/reject`.
 */
export interface Reject {
  /** Why the connection was refused. `unauthenticated` never distinguishes a missing credential from a wrong one. */
  readonly reason: RejectReason;
  /** A safe explanation for a person. Carries no credential material, no panic text, and no machine paths. */
  readonly detail: string;
  /** The major version this engine speaks, so a mismatched client can report what it needs. */
  readonly protocolMajor: number;
}

/** Maximum accepted length of `detail`, for bounded decoding. */
export const REJECT_DETAIL_MAX_LENGTH = 256;

/**
 * Welcome.
 *
 * The engine's answer to an accepted Hello. It states the selected protocol version, the engine session, and the limits this connection is bound by (108 section 6).
 *
 * Canonical schema: `mirae://ipc/v1/welcome`.
 */
export interface Welcome {
  /** Selected major version. Always the engine's own major version, since a mismatch is rejected instead. */
  readonly protocolMajor: number;
  /** Selected minor version: the highest both peers support (108 section 8.2). */
  readonly protocolMinor: number;
  /** Identifies this engine process lifetime, so a reconnecting client can tell whether its replicated state is stale. */
  readonly engineSessionId: string;
  /** Largest frame this connection accepts. A larger frame is rejected before it is allocated for (108 section 9). */
  readonly maxFrameBytes: number;
}

/** Maximum accepted length of `engineSessionId`, for bounded decoding. */
export const WELCOME_ENGINE_SESSION_ID_MAX_LENGTH = 64;

/**
 * PersistedProjectBody.
 *
 * The project's own content, separated from the envelope that describes the file. The split matters on open: the envelope is read and validated first, so a build can decide whether it may interpret the body at all (401 section 10).
 *
 * Canonical schema: `mirae://project/v1/persisted-project-body`.
 */
export interface PersistedProjectBody {
  /** Scenes, written in identifier order so the file is byte-stable across saves (401 section 12). */
  readonly scenes: readonly PersistedScene[];
  /** Source definitions, written in identifier order. */
  readonly sources: readonly PersistedSourceDefinition[];
  /** Scene items, written in identifier order. Bounded higher than scenes because a project has many more of them. */
  readonly sceneItems: readonly PersistedSceneItem[];
}

/** Maximum accepted number of `scenes` entries, for bounded decoding. */
export const PERSISTED_PROJECT_BODY_SCENES_MAX_ITEMS = 4096;

/** Maximum accepted number of `sources` entries, for bounded decoding. */
export const PERSISTED_PROJECT_BODY_SOURCES_MAX_ITEMS = 4096;

/** Maximum accepted number of `sceneItems` entries, for bounded decoding. */
export const PERSISTED_PROJECT_BODY_SCENE_ITEMS_MAX_ITEMS = 65536;

/**
 * PersistedProjectEnvelope.
 *
 * The whole project file: what it is, which schema it speaks, who wrote it, whether it is intact, and the project itself. The envelope exists so that an opening build can answer 'may I read this' before it tries to (401 sections 3 and 10).
 *
 * Canonical schema: `mirae://project/v1/persisted-project-envelope`.
 */
export interface PersistedProjectEnvelope {
  /** Identifies the file as a Mirae project. 401 invariant 1: a format identifies itself rather than relying on its extension. */
  readonly format: string;
  /** The project schema major version. Explicit, because a file that does not say what it is cannot be migrated (401 invariant 2). */
  readonly schemaVersion: number;
  /** Stable project identifier, as a canonical hyphenated UUID. Survives renames, moves, and copies (401 invariant 3). */
  readonly projectId: string;
  /** When the project was created, as an RFC 3339 timestamp. */
  readonly createdAt: string;
  /** When this file was written, as an RFC 3339 timestamp. */
  readonly lastSavedAt: string;
  /** Which Mirae versions wrote this file and which one it needs. */
  readonly app: ProjectAppVersions;
  /** Features this project requires. An unsupported entry is refused or opened read-only, never ignored (401 invariant 7). */
  readonly features: readonly string[];
  /** Corruption detection for this file. */
  readonly integrity: ProjectIntegrity;
  /** The project content itself. */
  readonly project: PersistedProjectBody;
}

/** Maximum accepted length of `format`, for bounded decoding. */
export const PERSISTED_PROJECT_ENVELOPE_FORMAT_MAX_LENGTH = 32;

/** The only accepted value of `schemaVersion`. */
export const PERSISTED_PROJECT_ENVELOPE_SCHEMA_VERSION = 1;

/** Maximum accepted length of `projectId`, for bounded decoding. */
export const PERSISTED_PROJECT_ENVELOPE_PROJECT_ID_MAX_LENGTH = 36;

/** Maximum accepted length of `createdAt`, for bounded decoding. */
export const PERSISTED_PROJECT_ENVELOPE_CREATED_AT_MAX_LENGTH = 64;

/** Maximum accepted length of `lastSavedAt`, for bounded decoding. */
export const PERSISTED_PROJECT_ENVELOPE_LAST_SAVED_AT_MAX_LENGTH = 64;

/** Maximum accepted number of `features` entries, for bounded decoding. */
export const PERSISTED_PROJECT_ENVELOPE_FEATURES_MAX_ITEMS = 256;

/**
 * PersistedScene.
 *
 * A scene as it is stored: identity, name, and the ordered scene items it composes. A scene is not a rendered image (005 section 3.2), so nothing here describes pixels.
 *
 * Canonical schema: `mirae://project/v1/persisted-scene`.
 */
export interface PersistedScene {
  /** Stable scene identifier, as a canonical hyphenated UUID (ADR-0069). */
  readonly id: string;
  /** Display name, bounded because it is user text read back from an untrusted file (005 section 8). */
  readonly name: string;
  /** Scene item identifiers in composition order. The order is the z-order, which is why it is a sequence rather than a field on each item. */
  readonly items: readonly string[];
}

/** Maximum accepted length of `id`, for bounded decoding. */
export const PERSISTED_SCENE_ID_MAX_LENGTH = 36;

/** Maximum accepted length of `name`, for bounded decoding. */
export const PERSISTED_SCENE_NAME_MAX_LENGTH = 256;

/** Maximum accepted number of `items` entries, for bounded decoding. */
export const PERSISTED_SCENE_ITEMS_MAX_ITEMS = 4096;

/**
 * PersistedSceneItem.
 *
 * The placement of a source inside a scene. Several items may reference one source definition, which is why the reference is an identifier rather than an embedded copy (005 section 3.4).
 *
 * Canonical schema: `mirae://project/v1/persisted-scene-item`.
 */
export interface PersistedSceneItem {
  /** Stable scene item identifier, as a canonical hyphenated UUID (ADR-0069). */
  readonly id: string;
  /** The scene this item belongs to. */
  readonly sceneId: string;
  /** The source definition this item places. */
  readonly sourceId: string;
  /** Whether this item participates in composition. */
  readonly visible: boolean;
}

/** Maximum accepted length of `id`, for bounded decoding. */
export const PERSISTED_SCENE_ITEM_ID_MAX_LENGTH = 36;

/** Maximum accepted length of `sceneId`, for bounded decoding. */
export const PERSISTED_SCENE_ITEM_SCENE_ID_MAX_LENGTH = 36;

/** Maximum accepted length of `sourceId`, for bounded decoding. */
export const PERSISTED_SCENE_ITEM_SOURCE_ID_MAX_LENGTH = 36;

/** What kind of source this is. A closed set: an unknown kind is a compatibility diagnostic rather than a field the engine guesses at. */
export type PersistedSourceDefinitionKind =
  | "color";

/**
 * PersistedSourceDefinition.
 *
 * A reusable source as it is stored. It holds configuration and never a live capture session, decoder, or socket: 005 section 3.3 keeps runtime objects out of anything that can be serialized, and credentials appear only as references.
 *
 * Canonical schema: `mirae://project/v1/persisted-source-definition`.
 */
export interface PersistedSourceDefinition {
  /** Stable source identifier, as a canonical hyphenated UUID (ADR-0069). */
  readonly id: string;
  /** Display name, bounded because it is user text read back from an untrusted file. */
  readonly name: string;
  /** What kind of source this is. A closed set: an unknown kind is a compatibility diagnostic rather than a field the engine guesses at. */
  readonly kind: PersistedSourceDefinitionKind;
}

/** Maximum accepted length of `id`, for bounded decoding. */
export const PERSISTED_SOURCE_DEFINITION_ID_MAX_LENGTH = 36;

/** Maximum accepted length of `name`, for bounded decoding. */
export const PERSISTED_SOURCE_DEFINITION_NAME_MAX_LENGTH = 256;

/**
 * ProjectAppVersions.
 *
 * Which Mirae versions wrote a project and which one it needs. `minimumVersion` is what an opening build compares itself against before it decides whether it can honour the file's required features (401 section 3).
 *
 * Canonical schema: `mirae://project/v1/project-app-versions`.
 */
export interface ProjectAppVersions {
  /** The oldest Mirae version that can open this project without losing intent. */
  readonly minimumVersion: string;
  /** The Mirae version that last wrote this file, recorded for diagnostics rather than for compatibility decisions. */
  readonly savedByVersion: string;
}

/** Maximum accepted length of `minimumVersion`, for bounded decoding. */
export const PROJECT_APP_VERSIONS_MINIMUM_VERSION_MAX_LENGTH = 32;

/** Maximum accepted length of `savedByVersion`, for bounded decoding. */
export const PROJECT_APP_VERSIONS_SAVED_BY_VERSION_MAX_LENGTH = 32;

/** The hash algorithm. A closed set, so an unknown algorithm is a rejection rather than a field nobody validates. */
export type ProjectIntegrityAlgorithm =
  | "sha256";

/**
 * ProjectIntegrity.
 *
 * Detects accidental corruption of a project file. Not authenticity: 401 section 11 is explicit that this is a checksum, not a signature, and a file that fails it is reported rather than trusted or silently repaired.
 *
 * Canonical schema: `mirae://project/v1/project-integrity`.
 */
export interface ProjectIntegrity {
  /** The hash algorithm. A closed set, so an unknown algorithm is a rejection rather than a field nobody validates. */
  readonly algorithm: ProjectIntegrityAlgorithm;
  /** Hash of the canonically serialized document with this field excluded, as lowercase hexadecimal (401 section 11). */
  readonly contentHash: string;
}

/** Maximum accepted length of `contentHash`, for bounded decoding. */
export const PROJECT_INTEGRITY_CONTENT_HASH_MAX_LENGTH = 128;

/**
 * RecoveryRecord.
 *
 * One autosaved snapshot, held separately from the canonical project file. It carries what recovery needs in order to classify a candidate on the next start: which project, which generation, when, and which explicit save it was based on (404 section 2).
 *
 * Canonical schema: `mirae://project/v1/recovery-record`.
 */
export interface RecoveryRecord {
  /** Identifies this record, as a canonical hyphenated UUID. */
  readonly recoveryId: string;
  /** The project this record belongs to. Recovery candidates are located by this, not by path: a project that moved is still the same project. */
  readonly projectId: string;
  /** The committed generation this record holds. 404 invariant 2: only committed generations are recorded, never a half-built edit. */
  readonly stateGeneration: number;
  /** When the record was written, as an RFC 3339 timestamp. */
  readonly recordedAt: string;
  /** The content hash of the explicit save this record builds on, or empty when the project has never been saved. 404 section 6 compares it to tell a useful candidate from one belonging to a version the user has since replaced. */
  readonly baseSaveHash: string;
  /** The Mirae version that wrote the record, for diagnostics. */
  readonly appVersion: string;
  /** The project as it stood at that generation. */
  readonly project: PersistedProjectEnvelope;
}

/** Maximum accepted length of `recoveryId`, for bounded decoding. */
export const RECOVERY_RECORD_RECOVERY_ID_MAX_LENGTH = 36;

/** Maximum accepted length of `projectId`, for bounded decoding. */
export const RECOVERY_RECORD_PROJECT_ID_MAX_LENGTH = 36;

/** Maximum accepted length of `recordedAt`, for bounded decoding. */
export const RECOVERY_RECORD_RECORDED_AT_MAX_LENGTH = 64;

/** Maximum accepted length of `baseSaveHash`, for bounded decoding. */
export const RECOVERY_RECORD_BASE_SAVE_HASH_MAX_LENGTH = 128;

/** Maximum accepted length of `appVersion`, for bounded decoding. */
export const RECOVERY_RECORD_APP_VERSION_MAX_LENGTH = 32;

/** Every contract id in this build, sorted. */
export const CONTRACT_IDS = [
  "mirae://ipc/v1/engine-readiness",
  "mirae://ipc/v1/hello",
  "mirae://ipc/v1/protocol-version",
  "mirae://ipc/v1/reject",
  "mirae://ipc/v1/welcome",
  "mirae://project/v1/persisted-project-body",
  "mirae://project/v1/persisted-project-envelope",
  "mirae://project/v1/persisted-scene",
  "mirae://project/v1/persisted-scene-item",
  "mirae://project/v1/persisted-source-definition",
  "mirae://project/v1/project-app-versions",
  "mirae://project/v1/project-integrity",
  "mirae://project/v1/recovery-record",
] as const;
