/**
 * Generated TypeScript contract bindings.
 *
 * @generated by `cargo xtask generate`. Do not edit by hand.
 * Regenerate with `cargo xtask generate` after changing a schema under
 * `schemas/`, and verify with `cargo xtask generate --check`.
 */

/** Lifecycle state. `degraded` means the engine is serving requests with reduced capability and the detail field explains what is missing. */
export type EngineReadinessState =
  | "starting"
  | "ready"
  | "degraded"
  | "stopping"
  | "stopped";

/**
 * Engine readiness.
 *
 * What the engine reports about its own lifecycle so the shell can decide whether to send work. No command is accepted before handshake completion, and readiness is not authorization (108 sections 6 and 11).
 *
 * Canonical schema: `mirae://ipc/v1/engine-readiness`.
 */
export interface EngineReadiness {
  /** Lifecycle state. `degraded` means the engine is serving requests with reduced capability and the detail field explains what is missing. */
  readonly state: EngineReadinessState;
  /** Major protocol version this engine speaks. */
  readonly protocolMajor: number;
  /** Minor protocol version this engine speaks. */
  readonly protocolMinor: number;
  /** Identifies one engine process lifetime. A reconnecting client presents the last session id it saw, and a different value means its replicated state is stale. */
  readonly engineSessionId: string;
  /** Optional safe explanation for a degraded or stopping state. Never carries panic text, secrets, or machine paths (108 section 14). */
  readonly detail?: string;
}

/** Maximum accepted length of `engineSessionId`, for bounded decoding. */
export const ENGINE_READINESS_ENGINE_SESSION_ID_MAX_LENGTH = 64;

/** Maximum accepted length of `detail`, for bounded decoding. */
export const ENGINE_READINESS_DETAIL_MAX_LENGTH = 256;

/**
 * Protocol version.
 *
 * The engine and shell protocol version. A major mismatch means an incompatible protocol and the connection is rejected; minor versions may add optional messages or fields, and the selected minor is the highest mutually supported one (108 section 8).
 *
 * Canonical schema: `mirae://ipc/v1/protocol-version`.
 */
export interface ProtocolVersion {
  /** Incompatible protocol generation. A peer that does not support this exact major version must be rejected. */
  readonly major: number;
  /** Backward-compatible revision within the major version. A higher minor may add optional messages and fields only. */
  readonly minor: number;
}

/** The only accepted value of `major`. */
export const PROTOCOL_VERSION_MAJOR = 1;

/** The only accepted value of `minor`. */
export const PROTOCOL_VERSION_MINOR = 0;

/** Every contract id in this build, sorted. */
export const CONTRACT_IDS = [
  "mirae://ipc/v1/engine-readiness",
  "mirae://ipc/v1/protocol-version",
] as const;
