//! Generated Rust contract bindings.
//!
//! @generated by `cargo xtask generate`. Do not edit by hand.
//! Regenerate with `cargo xtask generate` after changing a schema under
//! `schemas/`, and verify with `cargo xtask generate --check`.

/// Engine readiness.
///
/// What the engine reports about its own lifecycle so the shell can decide whether to send work. No command is accepted before handshake completion, and readiness is not authorization (108 sections 6 and 11).
///
/// Canonical schema: `mirae://ipc/v1/engine-readiness`.
///
/// See [`EngineReadinessState`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EngineReadiness {
    /// Lifecycle state. `degraded` means the engine is serving requests with reduced capability and the detail field explains what is missing.
    pub state: EngineReadinessState,
    /// Major protocol version this engine speaks.
    pub protocol_major: u16,
    /// Minor protocol version this engine speaks.
    pub protocol_minor: u16,
    /// Identifies one engine process lifetime. A reconnecting client presents the last session id it saw, and a different value means its replicated state is stale.
    ///
    /// Bounded to 64 characters by the schema.
    pub engine_session_id: String,
    /// Optional safe explanation for a degraded or stopping state. Never carries panic text, secrets, or machine paths (108 section 14).
    ///
    /// Bounded to 256 characters by the schema.
    pub detail: Option<String>,
}

/// Lifecycle state. `degraded` means the engine is serving requests with reduced capability and the detail field explains what is missing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EngineReadinessState {
    /// The `starting` value of `state`.
    Starting,
    /// The `ready` value of `state`.
    Ready,
    /// The `degraded` value of `state`.
    Degraded,
    /// The `stopping` value of `state`.
    Stopping,
    /// The `stopped` value of `state`.
    Stopped,
}

impl EngineReadinessState {
    /// The value as written on the wire.
    #[must_use]
    pub const fn as_wire_str(self) -> &'static str {
        match self {
            Self::Starting => "starting",
            Self::Ready => "ready",
            Self::Degraded => "degraded",
            Self::Stopping => "stopping",
            Self::Stopped => "stopped",
        }
    }
}

/// Maximum accepted length of `engineSessionId`, for bounded decoding.
pub const ENGINE_READINESS_ENGINE_SESSION_ID_MAX_LENGTH: usize = 64;

/// Maximum accepted length of `detail`, for bounded decoding.
pub const ENGINE_READINESS_DETAIL_MAX_LENGTH: usize = 256;

/// Protocol version.
///
/// The engine and shell protocol version. A major mismatch means an incompatible protocol and the connection is rejected; minor versions may add optional messages or fields, and the selected minor is the highest mutually supported one (108 section 8).
///
/// Canonical schema: `mirae://ipc/v1/protocol-version`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProtocolVersion {
    /// Incompatible protocol generation. A peer that does not support this exact major version must be rejected.
    pub major: u16,
    /// Backward-compatible revision within the major version. A higher minor may add optional messages and fields only.
    pub minor: u16,
}

/// The only accepted value of `major`.
pub const PROTOCOL_VERSION_MAJOR: u16 = 1;

/// The only accepted value of `minor`.
pub const PROTOCOL_VERSION_MINOR: u16 = 0;

/// Every contract id in this build, sorted.
pub const CONTRACT_IDS: [&str; 2] = [
    "mirae://ipc/v1/engine-readiness",
    "mirae://ipc/v1/protocol-version",
];
